[package]
name = "webgl"
version.workspace = true
description = "An example showing Vello Hybrid using WebGL2."
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
js-sys = "0.3.77"
log = { workspace = true }
vello_common = { workspace = true }
vello_hybrid = { workspace = true }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = [
    "Window",
    "HtmlCanvasElement",
    "CssStyleDeclaration",
    "WebGl2RenderingContext",
] }
wgpu = { workspace = true, features = ["webgl"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
