[package]
name = "vello_bench"
description = "Benchmarking harness for sparse strips."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["rlib", "cdylib"]
test = false

[dependencies]
fearless_simd = { workspace = true, features = ["force_support_fallback"] }
image = { workspace = true, features = ["jpeg"] }
parley = { version = "0.11.0", default-features = false, features = ["std"] }
usvg = { workspace = true }
vello_common = { workspace = true }
vello_cpu = { workspace = true }
vello_dev_macros = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
smallvec = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = "0.8.9"

[[bin]]
name = "vello-bench"
path = "src/bin/cli.rs"

[[test]]
name = "allocations"
harness = false

[lints]
workspace = true
