// Copyright 2026 the Vello Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

#[cfg(not(target_arch = "wasm32"))]
mod tests {
    use vello_common::color;
    use vello_common::filter_effects::{EdgeMode, Filter, FilterPrimitive};
    use vello_common::geometry::RectU16;
    use vello_common::kurbo::{Affine, Circle, Rect, Shape};
    use vello_common::peniko::ImageQuality;
    use vello_hybrid::SampleRect;

    use crate::load_image;

    use crate::renderer::{HybridRenderer, Renderer};
    use crate::util::{check_ref, get_ctx};
    use vello_cpu::RenderMode;

    const SPRITES: [RectU16; 4] = [
        // Checkmark.
        RectU16::new(0, 0, 56, 56),
        // Eyes
        RectU16::new(56, 0, 112, 42),
        // Confetti
        RectU16::new(0, 56, 54, 112),
        // Cowboy Hat Face
        RectU16::new(56, 42, 115, 100),
    ];

    /// A (temporary?) helper to test [`vello_hybrid`], where the snapshot is generated by
    /// [`vello_hybrid`] specifically.
    ///
    /// Necessary, because currently the [`vello_dev_macros::vello_test`] macro generates the snapshot
    /// using [`vello_cpu`].
    fn hybrid_snapshot_test<const WIDTH: u16, const HEIGHT: u16>(
        test_name: &str,
        f: impl FnOnce(&mut HybridRenderer),
    ) {
        let mut ctx = get_ctx::<HybridRenderer>(
            WIDTH,
            HEIGHT,
            false,
            0,
            "fallback",
            RenderMode::OptimizeSpeed,
            false,
        );
        f(&mut ctx);
        let specific_name = format!("{test_name}_hybrid");
        // Set `diff_pixels` to `3`: we can't generate a "golden standard" using `f32` on `vello_cpu` as
        // it doesn't implement the tested functionality yet.
        check_ref(&mut ctx, test_name, &specific_name, 3, 0, true, &[]);
    }

    #[test]
    fn external_texture_composite() {
        hybrid_snapshot_test::<96, 96>("external_texture_composite", |ctx| {
            let texture_id = ctx.register_external_texture(load_image!("glyphs_colr_noto"));
            ctx.draw_texture_rects(
                texture_id,
                ImageQuality::Low,
                [SampleRect {
                    source_region: SPRITES[0],
                    transform: Affine::translate((12., 15.)),
                }],
            );
            ctx.set_paint(color::palette::css::PALE_GOLDENROD.with_alpha(0.7));
            ctx.fill_rect(&Rect::new(10., 7., 65., 55.));
            ctx.draw_texture_rects(
                texture_id,
                ImageQuality::Low,
                [SampleRect {
                    source_region: SPRITES[3],
                    transform: Affine::translate((25., 25.)),
                }],
            );
        });
    }

    #[test]
    fn external_texture_skewed() {
        hybrid_snapshot_test::<96, 96>("external_texture_skewed", |ctx| {
            let texture_id = ctx.register_external_texture(load_image!("glyphs_colr_noto"));
            ctx.draw_texture_rects(
                texture_id,
                ImageQuality::High,
                [SampleRect {
                    source_region: SPRITES[0],
                    transform: Affine::translate((15., 15.)) * Affine::skew(0.2, 0.1),
                }],
            );
        });
    }

    #[test]
    fn external_texture_clipped() {
        hybrid_snapshot_test::<96, 96>("external_texture_clipped", |ctx| {
            let texture_id = ctx.register_external_texture(load_image!("glyphs_colr_noto"));
            let clip = Circle::new((48., 48.), 24.).to_path(0.1);

            ctx.push_clip_layer(&clip);
            ctx.draw_texture_rects(
                texture_id,
                ImageQuality::Medium,
                [
                    SampleRect {
                        source_region: SPRITES[1],
                        transform: Affine::translate((18., 18.)),
                    },
                    SampleRect {
                        source_region: SPRITES[3],
                        transform: Affine::translate((34., 34.)),
                    },
                ],
            );
            ctx.pop_layer();
        });
    }

    #[test]
    fn external_texture_blurred() {
        hybrid_snapshot_test::<96, 96>("external_texture_blurred", |ctx| {
            let texture_id = ctx.register_external_texture(load_image!("glyphs_colr_noto"));
            let blur = Filter::from_primitive(FilterPrimitive::GaussianBlur {
                std_deviation: 4.0,
                edge_mode: EdgeMode::None,
            });

            ctx.push_filter_layer(blur);
            ctx.draw_texture_rects(
                texture_id,
                ImageQuality::Low,
                [SampleRect {
                    source_region: SPRITES[2],
                    transform: Affine::translate((20., 20.)),
                }],
            );
            ctx.pop_layer();
        });
    }

    #[test]
    fn external_texture_many_sprites() {
        hybrid_snapshot_test::<192, 132>("external_texture_many_sprites", |ctx| {
            let texture_id = ctx.register_external_texture(load_image!("glyphs_colr_noto"));
            let placements = [
                (SPRITES[0], 8., 10.),
                (SPRITES[1], 34., 12.),
                (SPRITES[2], 56., 10.),
                (SPRITES[3], 80., 8.),
                (SPRITES[0], 106., 11.),
                (SPRITES[2], 130., 9.),
                (SPRITES[1], 10., 66.),
                (SPRITES[3], 34., 64.),
                (SPRITES[0], 58., 68.),
                (SPRITES[2], 84., 66.),
                (SPRITES[3], 110., 64.),
                (SPRITES[1], 134., 67.),
            ];

            ctx.draw_texture_rects(
                texture_id,
                ImageQuality::Low,
                placements.map(|(source_region, x, y)| SampleRect {
                    source_region,
                    transform: Affine::translate((x, y)),
                }),
            );
        });
    }

    #[test]
    fn external_texture_with_scene_transform() {
        hybrid_snapshot_test::<96, 96>("external_texture_with_scene_transform", |ctx| {
            let texture_id = ctx.register_external_texture(load_image!("glyphs_colr_noto"));

            ctx.set_transform(
                Affine::translate((20., 0.))
                    * Affine::rotate(0.35)
                    * Affine::scale_non_uniform(0.85, 1.1),
            );
            ctx.draw_texture_rects(
                texture_id,
                ImageQuality::Medium,
                [
                    SampleRect {
                        source_region: SPRITES[0],
                        transform: Affine::translate((6., 8.)),
                    },
                    SampleRect {
                        source_region: SPRITES[3],
                        transform: Affine::translate((28., 5.)) * Affine::skew(0.18, -0.08),
                    },
                    SampleRect {
                        source_region: SPRITES[2],
                        transform: Affine::translate((48., 6.)),
                    },
                ],
            );
        });
    }
}
