[package]
name = "run_wasm"
version.workspace = true
edition.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-run-wasm = { git = "https://github.com/rukai/cargo-run-wasm", rev = "4913e01537ad103a057352bf7bbb1cd96a1bb4b5" }
