[package]
name = "vello_toy"
description = "A collection of different binary crates for interacting with the sparse rendering stack."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
svg = { workspace = true }
usvg = { workspace = true }
clap = { workspace = true, features = ["derive"] }
vello_common = { workspace = true }
vello_cpu = { workspace = true }
peniko = { workspace = true }
image = { workspace = true, features = ["png"] }

[[bin]]
name = "debug"
path = "src/debug.rs"

[[bin]]
name = "svg"
path = "src/svg.rs"

[lints]
workspace = true
