[package]
name = "vello_toy"
version.workspace = true
description = "A collection of different binary crates for interacting with the sparse rendering stack."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
# Prevent accidental publishing until the initial release
publish = false

[dependencies]
svg = { workspace = true }
clap = { workspace = true, features = ["derive"] }
vello_common = { workspace = true }

[[bin]]
name = "debug"
path = "src/debug.rs"

[lints]
workspace = true
