[package]
name = "vello_toy"
description = "A collection of different binary crates for interacting with the sparse rendering stack."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
svg = { workspace = true }
clap = { workspace = true, features = ["derive"] }
# TODO: Should vello_toy be `no_std`?
vello_common = { workspace = true, features = ["std"] }

[[bin]]
name = "debug"
path = "src/debug.rs"

[lints]
workspace = true
