[package]
name = "simple_sdl3"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

# The dependencies here are independent from the workspace versions
[dependencies]
# When using this example outside of the original Vello workspace,
# remove the path property of the following Vello dependency requirement.
vello = { version = "0.10.0", path = "../../vello_research" }
pollster = "0.4.0"

[target.'cfg(target_os = "windows")'.dependencies]
sdl3 = { version = "0.20.0", features = ["raw-window-handle", "build-from-source-static"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
sdl3 = { version = "0.20.0", features = ["raw-window-handle", "use-pkg-config"] }
