[package]
name = "wgpu_webgpu"
version.workspace = true
description = "An example showing Vello GPU using WebGPU through wgpu."
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
log = { workspace = true }
vello_common = { workspace = true }
vello_gpu = { workspace = true, features = ["text", "wgpu", "wgpu_default"] }
vello_example_scenes = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = [
    "Window",
    "Location",
    "History",
    "UrlSearchParams",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "CssStyleDeclaration",
    "MouseEvent",
    "WheelEvent",
    "KeyboardEvent",
] }
wgpu = { workspace = true, default-features = true, features = ["webgpu"] }
