// Copyright 2026 the Vello Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Lint pass: vertex inputs at user-defined locations must not use signed or
//! unsigned integer types.
//!
//! Some Intel HD Graphics 4000 macOS/ANGLE combinations silently route
//! buffer-backed integer vertex attributes through a floating-point conversion.
//! Observed affected Chrome versions include 104+ on Catalina, 100+ on Mojave,
//! and 100–103 on El Capitan; this list is not exhaustive.
//! WebGL still reports the attribute as integer, but the shader receives the
//! bit pattern of the numerically converted float. Fetch packed values through
//! floating-point attributes instead and reconstruct them in the vertex shader.

use naga::{Binding, Module, ScalarKind, ShaderStage, TypeInner};

use super::LintReport;

/// Detects integer-typed, user-defined inputs to all vertex entry points.
///
/// Built-ins such as `@builtin(vertex_index) vertex_index: u32` are generated by
/// the API rather than fetched from a vertex buffer, so they are deliberately
/// allowed.
pub(super) fn check(module: &Module) -> Option<LintReport> {
    let mut violations = Vec::new();

    for entry_point in module
        .entry_points
        .iter()
        .filter(|entry_point| entry_point.stage == ShaderStage::Vertex)
    {
        for (argument_index, argument) in entry_point.function.arguments.iter().enumerate() {
            let argument_name = argument.name.as_deref().unwrap_or("<unnamed>");
            match &argument.binding {
                Some(binding) => check_input(
                    module,
                    &entry_point.name,
                    &format!("argument #{argument_index} (`{argument_name}`)"),
                    binding,
                    argument.ty,
                    &mut violations,
                ),
                None => {
                    if let TypeInner::Struct { members, .. } = &module.types[argument.ty].inner {
                        for (member_index, member) in members.iter().enumerate() {
                            let Some(binding) = &member.binding else {
                                continue;
                            };
                            let member_name = member.name.as_deref().unwrap_or("<unnamed>");
                            check_input(
                                module,
                                &entry_point.name,
                                &format!(
                                    "argument #{argument_index} (`{argument_name}`), member \
                                     #{member_index} (`{member_name}`)"
                                ),
                                binding,
                                member.ty,
                                &mut violations,
                            );
                        }
                    }
                }
            }
        }
    }

    if violations.is_empty() {
        return None;
    }

    Some(LintReport {
        summary: "uses signed or unsigned integer vertex inputs at user-defined locations.",
        explanation: "Buffer-backed integer vertex attributes are corrupted on some Intel HD \
                      Graphics 4000 macOS/ANGLE combinations: the values pass through a numeric \
                      floating-point conversion despite being configured as integer attributes. \
                      Observed affected Chrome versions include 104+ on Catalina, 100+ on \
                      Mojave, and 100-103 on El Capitan (non-exhaustive). \
                      Declare each vertex input as `f32` (or a float vector), fetch it through the \
                      floating-point vertex-attribute path, and recover packed bits with \
                      `bitcast<u32>`. Integer built-ins and integer values produced inside the \
                      vertex shader remain safe.",
        violations,
    })
}

fn check_input(
    module: &Module,
    entry_point_name: &str,
    input_label: &str,
    binding: &Binding,
    ty: naga::Handle<naga::Type>,
    violations: &mut Vec<String>,
) {
    let Binding::Location { location, .. } = binding else {
        return;
    };

    let kind = match module.types[ty].inner {
        TypeInner::Scalar(scalar) | TypeInner::Vector { scalar, .. } => scalar.kind,
        _ => return,
    };
    if !matches!(kind, ScalarKind::Sint | ScalarKind::Uint) {
        return;
    }

    violations.push(format!(
        "vertex entry point `{entry_point_name}`: {input_label} at location {location} has {} type `{}`",
        match kind {
            ScalarKind::Sint => "signed integer",
            ScalarKind::Uint => "unsigned integer",
            _ => unreachable!(),
        },
        type_name(module, ty),
    ));
}

fn type_name(module: &Module, ty: naga::Handle<naga::Type>) -> String {
    if let Some(name) = &module.types[ty].name {
        return name.clone();
    }

    match module.types[ty].inner {
        TypeInner::Scalar(scalar) => scalar_name(scalar.kind, scalar.width),
        TypeInner::Vector { size, scalar } => format!(
            "vec{}<{}>",
            u8::from(size),
            scalar_name(scalar.kind, scalar.width),
        ),
        ref inner => format!("{inner:?}"),
    }
}

fn scalar_name(kind: ScalarKind, width: naga::Bytes) -> String {
    let prefix = match kind {
        ScalarKind::Sint => "i",
        ScalarKind::Uint => "u",
        ScalarKind::Float => "f",
        ScalarKind::Bool => return "bool".to_string(),
        ScalarKind::AbstractInt => "abstract-int-",
        ScalarKind::AbstractFloat => "abstract-float-",
    };
    format!("{prefix}{}", width * 8)
}

#[cfg(test)]
mod tests {
    use naga::{Module, front::wgsl};

    use super::super::lint;

    const FLOAT_VERTEX_INPUTS: &str = r#"
struct VertexInput {
    @location(0) scalar: f32,
    @location(1) vector: vec2<f32>,
}

@vertex
fn vs_main(
    @builtin(vertex_index) vertex_index: u32,
    input: VertexInput,
) -> @builtin(position) vec4<f32> {
    return vec4<f32>(input.scalar, input.vector, f32(vertex_index));
}

@fragment
fn fs_main() -> @location(0) vec4<f32> {
    return vec4<f32>(0.0);
}
"#;

    const DIRECT_UNSIGNED_INPUT: &str = r#"
@vertex
fn vs_main(@location(3) packed: u32) -> @builtin(position) vec4<f32> {
    return vec4<f32>(f32(packed));
}

@fragment
fn fs_main() -> @location(0) vec4<f32> {
    return vec4<f32>(0.0);
}
"#;

    const STRUCT_SIGNED_INPUT: &str = r#"
struct VertexInput {
    @location(0) position: vec2<f32>,
    @location(4) packed: vec2<i32>,
}

@vertex
fn vs_main(input: VertexInput) -> @builtin(position) vec4<f32> {
    return vec4<f32>(input.position, vec2<f32>(input.packed));
}

@fragment
fn fs_main() -> @location(0) vec4<f32> {
    return vec4<f32>(0.0);
}
"#;

    const ALIASED_UNSIGNED_INPUT: &str = r#"
alias Packed = u32;

@vertex
fn vs_main(@location(2) packed: Packed) -> @builtin(position) vec4<f32> {
    return vec4<f32>(f32(packed));
}

@fragment
fn fs_main() -> @location(0) vec4<f32> {
    return vec4<f32>(0.0);
}
"#;

    fn parse(source: &str) -> Module {
        wgsl::parse_str(source).expect("WGSL parses")
    }

    #[test]
    fn accepts_float_vertex_inputs_and_integer_builtins() {
        lint("float_inputs", &parse(FLOAT_VERTEX_INPUTS));
    }

    #[test]
    #[should_panic(expected = "location 3 has unsigned integer type")]
    fn rejects_direct_unsigned_integer_vertex_input() {
        lint("unsigned_input", &parse(DIRECT_UNSIGNED_INPUT));
    }

    #[test]
    #[should_panic(expected = "location 4 has signed integer type")]
    fn rejects_signed_integer_vertex_input_in_struct() {
        lint("signed_input", &parse(STRUCT_SIGNED_INPUT));
    }

    #[test]
    #[should_panic(expected = "location 2 has unsigned integer type")]
    fn rejects_aliased_unsigned_integer_vertex_input() {
        lint("aliased_unsigned_input", &parse(ALIASED_UNSIGNED_INPUT));
    }
}
