[package]
name = "vello_filters_cpu"
version.workspace = true
categories = ["rendering", "graphics"]
keywords = ["2d", "render", "filter", "blur"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
# Prevent accidental publishing until the initial release
publish = false

[features]
default = ["std"]
std = ["color/std"]
libm = ["color/libm"]

[dependencies]
# tracing = { version = "0.1.41", default-features = false }
color = { version = "0.2.3", default-features = false }
transpose = "0.2.3"

[lints]
workspace = true
