on:
  pull_request:
    branches-ignore:
     - main

jobs:
  push-shaders:
    runs-on: windows-latest
    name: compile shaders
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/shader
